---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metrics

resources:
- prometheus.yaml
- role-bindings.yaml
- roles.yaml
- rules.yaml
- service-monitor.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    prometheus: mw
