---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metrics

resources:
- daemon-set.yaml
- service-monitor.yaml
- service.yaml

labels:
- includeSelectors: true
  pairs:
    app: node-exporter
